/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Hashtag {
  'name' : string,
  'createdAt' : Time,
  'usageCount' : bigint,
}
export type PublicationState = { 'published' : null } |
  { 'unpublished' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoIdea {
  'status' : VideoStatus,
  'title' : string,
  'hashtags' : Array<string>,
  'scheduledDate' : [] | [Time],
  'createdAt' : Time,
  'description' : string,
  'lastModified' : Time,
}
export type VideoStatus = { 'scheduled' : null } |
  { 'published' : null } |
  { 'draft' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHashtag' : ActorMethod<[string], undefined>,
  'addVideoIdea' : ActorMethod<[string, string, Array<string>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDraft' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHashtags' : ActorMethod<[], Array<Hashtag>>,
  'getPublicationState' : ActorMethod<[], PublicationState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoIdeas' : ActorMethod<[], Array<VideoIdea>>,
  'getVideosByDateRange' : ActorMethod<[Time, Time], Array<VideoIdea>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleVideoIdea' : ActorMethod<[string, Time], undefined>,
  'togglePublicationState' : ActorMethod<[], PublicationState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];