/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const Hashtag = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'usageCount' : IDL.Nat,
});
export const PublicationState = IDL.Variant({
  'published' : IDL.Null,
  'unpublished' : IDL.Null,
});
export const VideoStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const VideoIdea = IDL.Record({
  'status' : VideoStatus,
  'title' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'scheduledDate' : IDL.Opt(Time),
  'createdAt' : Time,
  'description' : IDL.Text,
  'lastModified' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHashtag' : IDL.Func([IDL.Text], [], []),
  'addVideoIdea' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDraft' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHashtags' : IDL.Func([], [IDL.Vec(Hashtag)], ['query']),
  'getPublicationState' : IDL.Func([], [PublicationState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoIdeas' : IDL.Func([], [IDL.Vec(VideoIdea)], ['query']),
  'getVideosByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(VideoIdea)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleVideoIdea' : IDL.Func([IDL.Text, Time], [], []),
  'togglePublicationState' : IDL.Func([], [PublicationState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const Hashtag = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'usageCount' : IDL.Nat,
  });
  const PublicationState = IDL.Variant({
    'published' : IDL.Null,
    'unpublished' : IDL.Null,
  });
  const VideoStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const VideoIdea = IDL.Record({
    'status' : VideoStatus,
    'title' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'scheduledDate' : IDL.Opt(Time),
    'createdAt' : Time,
    'description' : IDL.Text,
    'lastModified' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHashtag' : IDL.Func([IDL.Text], [], []),
    'addVideoIdea' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDraft' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHashtags' : IDL.Func([], [IDL.Vec(Hashtag)], ['query']),
    'getPublicationState' : IDL.Func([], [PublicationState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoIdeas' : IDL.Func([], [IDL.Vec(VideoIdea)], ['query']),
    'getVideosByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(VideoIdea)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleVideoIdea' : IDL.Func([IDL.Text, Time], [], []),
    'togglePublicationState' : IDL.Func([], [PublicationState], []),
  });
};

export const init = ({ IDL }) => { return []; };